### ISSUE TITLE
Goauld plasma defense guns dont shoot

### ISSUE THREAD

**Issue by panzer1b** [StargateInvasion/SGI#103]
Pretty much when constructing the goauld plasma gun: Goauld_Orbital_WeaponsPlatform.entity it never fires at anything and does not appear to use any of its abilities either making it a expensive paperweight.  Its abilities work and deal damage when manually activated, but sofar ive not seen them activated automatically when ships enter range, and they 100% will not shoot their gun at all even when i click attack this target that is at point blank range.

A bit unrelated, but most of the goauld defenses (particularly the plasma gun and hangar are pathetically weak and lack both survivability and damage output in general.  That is fine if the idea is to make goauld weapons seem inferior (most of their tech was cannon fodder in the show), but they need to be far cheaper and take up less slots to compensate for their considerably weaker performance (both in raw damage output and in non existent defensive ability).

**Comment by tanknnru** [comment]
Autoattack ability broken completly. Weapon platform just do not have any attack range at all.

**Comment by jeffg2k** [comment]
Should hopefully be resolved now.
