### ISSUE TITLE
balancing issues

### ISSUE THREAD

**Issue by panzer1b** [StargateInvasion/SGI#104]
Well ive been using this mod for some time now (my favorite sins mod period as of this point) and would like to share my experience with attempts at balancing the different factions to not be completely 1 sided.

My testing has thusfar been mostly AI vs AI, 2v2 games where there are 2 locked teams, 3v2 and im on the 3 side but do not actually play agressively (just take 3-4 planets near the home and purely lock them down defensively).  Essentially this becomes (i make sure to always have my own spawn between the 2 allys) a 2v2 AI vs AI with no or very minimal human intervention.  In this environment ive come to the following conclusions, some of which may be bugs, some of which may be balance issues:

*asurans (happens with goauld too but less often) occasionally get "stuck" early game where they loose their ships (specifically their destiny class or the colony one for goaulds) and then do not build more ships in a timely fashion to overcome their losses.  If the enemy capitalizes on this early game they can flatten the asurans by just walking over them unopposed with the exception of defensive structures that wont really do much against a whole fleet even if asurans have the best defenses in game.  It doesnt happen always, but when it does its game over for that AI player.

*asuran and human shield research is extremely overpowered, and any AI that does not invest in researching that technology is almost guaranteed to loose (and from what ove seen goauld are the least likely to invest into shield research, which compunds upon them being the weakest faction in the 1st place).  Its good that there is a noteable difference between unresearched and fully maxed out, but that difference is so huge and AI doesnt know the fact that it it does not research max shields it is going to be anihilated.  Finally, the shield mitigation needs to be lowered by ~50% for both humans and asurans, since it makes it almost impossible to do anything to them late game unless you yourself have that research.

*Continuing the above point, researching has way too much dominance in game results.  I know it would be a major undertaking, but i strongly suggest if at all possible to balance factions based on base stats more then end game max research (with some quirks along the way like unlocking human beam guns).  This is because the AI is just not smart enough to know what researches are essential to being competitive (specifically you NEED max shields, max resource extraction, and a good deal into weapons for some factions like asurans and their drone shield bypass as well as human beams).

*goaulds are overall way too weak with a few rare exceptions.  They have some very powerful abilities and ship combos (hatel disable ships ability especially at LV3, also shared by humans on their achilles), but overall most of their ships, especially capitals like the shutak are just useless in a actual fight against either asurans or humans past early game before they have shield mitigation and high powered guns.  Ive found that hatel spam is one of the better tactics (as they can disable ships for a very long time when leveled), supplemented by alot of fodder like the horus purely to keep the enemy's attention off your capitals.

*Along those lines, humans are extremely limited in viable ship choices.  They have alot of vessels available to them, but the only viable strat that ive seen working there is rushing the titan research and then spamming 304s (which have the best damage per cost/slots cause of their beams) like crazy supplemented by a handful of capital ships, specifically achilles for the broken disable enemy ships ability and the one with the green asuran beam weapon on it against structures late game (forgot name of this one).  Most ships like the morpheus and the other mid game cruisers are nothing more then cannon fodder for the enemy compared to 304s.

Anyways, since i know how to mod games myself (and really liked this mod), i made a few changes to my own version of the game to try and fix this without a complete overhaul of the mod:

*changed asuran and human shields research to have 1/2 as much benefit in every stat.  This seems to bring the races shields more in line with each other, and it also makes it so you nolonger have so much crazy shield mitigation that makes the only really effective weapon against it drone spam with their shield bypass capability.

*removed all prebuilt structures from the start of a game around a faction's home planet.  This seems to have fixed 90% of the AI hangs at the start of the game (cause they dont seem willing to build colonizer ships or essential research structures otherwise).  Also removed any ships that spawn there with the exception of the normal 2 scout vessels when on fast start mode which seems to make the AI upgrade their fleet capacity sooner then when they start with lots of ships.

*made goauld ship research nolonger locked behind heroes.  Seems that the AI cant use heroes at all (or well ive never seen them using them) and hforcing the already weakest faction to do twice as much research to get access to all of their capital ships excessively punishing (on both asurans and meatbags heroes are optional research not locked behind anything else which makes it a option and not a requirement to put the points into said research).

Anyways, the above seems to have adjusted the major cause of imbalance and the shield /research change seems to have really helped the goauld be less useless later in the game (they have very good early game capability, but become nothing more then worthless near the end).  Not meant to pressure you guys to change the mod or anything, but i just wanted to throw in my suggestions for future development with regards to balance.

**Comment by jeffg2k** [comment]
Thanks for the feedback! If you want to do a pull request to the repository, @VikingWarriorGaming can take a look.  He's working on making the game more balanced.  On March 2nd, I pushed an update to try and make the AI research heroes.  You can set priority to various research items so I wonder if giving shields and resources a higher priority would also help.  One thing I've found with the Asurans is that as soon as the shields run out, you better get moving as their hull goes down quickly.

**Comment by panzer1b** [comment]
Ok, so i believe ive sorta accomplished workable balance between 3 factions thusfar, AND ive 100% fixed the AI hangs that result in AI refusing to construct warships on start occasionally.  Its actually alot more fun now, and yeah, i dont know why but i juts love how fast paced this is compared to stock or even that other stargate mod with raiths and oris and other factions available in it.

I did my absolute best with regards to changing a few weapon stats to try and bring the overperformers into line and to make the weakest ships actually useful.  Notable changes are:
*304 beam damage cut down to be similar to the nyx
*sokar ship gets much stronger shields, and ability to engage much larger number of ships at a time (i wanted to give it way more firepower without making it into a clone of the anubis, and letting it hit 4 ships per side does that very well).
*boosted hephestus shields (to compensate for shield research being much weaker).
*nerf to human emp/jamming ability (it still stops ships in their tracks but doesnt disable their ability to return fire, gouald is as was since they are weaker anyway).
*redone human research to force them to take plasma guns to obtain beams (after balancing they sorta need the plasma pulse guns to compete with rest).

I also made a bit of an overhaul to weapon fx.  I made the guns look closer to what was in the show in terms of how fast they fire and what sort of damage they do.  As example, i severely lowered the quantity of drones spit out by the replicator ships since those things were very very powerful in lore (a salvo of them could annihilate a entire ship reliably), and i sorta normalized the quantities fired based on how much damage guns are doing (so a ship that spits out twice as many drones per salvo ends up doing 2x the damage in HP).  Another thing i did was redo the human railguns/autoguns/whatever the fast firing guns were to make them fire in more pronounced bursts which looks much cooler and is more true to the show as well as changed muzzle flash of the blue railguns to be blue.  This is obviously purely asthetic, but the biggest eyesore imo was looking at the ceres vs the caleus (and a few other replicator ships), former fired 6 drones and did 120 damage per second, and latter fired 30 drones and did 60 dps with its drones, now the former fires 12, and the latter fires 6 which is far more realistic).

Anyways, here is what i came up with (its a mod to your mod).  Will take some time to make it perfect, but at least its a start that you guys can try and make progress on.

[SGI-rebalance.zip](https://github.com/StargateInvasion/SGI/files/3221276/SGI-rebalance.zip)

**Comment by jeffg2k** [comment]
@panzer1b I've extracted your updates from the zip and applied them in a new branch for team review and merging into the base game.

**Comment by jeffg2k** [comment]
As an additional note, if this is something you enjoy and would like to help with balance and other aspects of the game as we build in the wraith and asgard, reach out to @AceFighter in the Discord forum.  We could always use some additional hands trying to get this mod completed.
