### ISSUE TITLE
TXT to BIN

### ISSUE THREAD

**Issue by NLArmy** [StargateInvasion/SGI#115]
Converting all ENTITY, MESH, PARTICLE and BRUSHES files to Binary to improve performance in next updates?

**Comment by jeffg2k** [comment]
We will not be doing that on the GitHub repository as we need them in plain text to easily modify and code them.  It also prevents the git compare from seeing what has changed on each commit as binaries don't diff on the site.  I think the binary improves load performance, but not sure it does anything for overall game performance.  If you would like it bin'd, we do so with the upload to [Moddb.com](https://www.moddb.com/mods/stargate-invasion/downloads) - however, we only update that periodically on major updates.  You can also bin the files yourself if you'd like, there is a script [convert.py](https://github.com/StargateInvasion/SinsModCheck/blob/master/convert.py) that can easily bin the entire mod.  It's what I use for the moddb distribution.
