### ISSUE TITLE
Network error when trying to download SGI

### ISSUE THREAD

**Issue by sgiuser** [StargateInvasion/SGI#116]
So I have been trying to download it direct as a ZIP file.
It downloads to around the 1GB size and then always stops. theres no other way around it that I can see.
I just want to download the zip file - can someone help?

**Comment by jeffg2k** [comment]
Perhaps a limitation of GitHub?  Never heard of an issue, but that is out our control.  I can only recommend downloading a clone of the repo https://github.com/StargateInvasion/SGI/wiki/Installation or trying to get SGI from moddb.

**Comment by jeffg2k** [comment]
Just tested the zip download myself and got 1.75Gb and looks like everything is there.  So maybe it's something with your network / system.
