### ISSUE TITLE
install  crashing  game

### ISSUE THREAD

**Issue by jhuddle1** [StargateInvasion/SGI#117]
every time I enable the mod it crashes the game dont know why ?

**Comment by jhuddle1** [comment]
This is my dump file, I dont understand it, hoping someone can help

[Sins-Rebellion v1.93-2019-12-17-23-41-03-15452-19972.zip](https://github.com/StargateInvasion/SGI/files/3977226/Sins-Rebellion.v1.93-2019-12-17-23-41-03-15452-19972.zip)

**Comment by jeffg2k** [comment]
We just pushed a new build to master which has higher requirements.  Haven't seen issues but perhaps it's not liking your system with the new graphics?  

You could try cloning it again in case it's incomplete or switching to the legacy branch.  At what point does it crash?

**Comment by jhuddle1** [comment]
it crashes once it loads the splash screen, what can I do to get it to  work ? its not liking my system with the new graphics ? I got the latest version of the game, running a gtx 1060 34 gb ram, and a i7 skylake 6700

**Comment by jhuddle1** [comment]
also have all my graphics turned up to max on the game

**Comment by jhuddle1** [comment]
switching to the legacy branch ????

**Comment by jhuddle1** [comment]
turns out I was running 1.93 so I installed 1.94 problem solved

**Comment by jeffg2k** [comment]
Glad you figured it out as I was scratching my head. :)

**Comment by jhuddle1** [comment]
yeah, I noticed the wraith finally got released, I am glad to see them
ingame. I  am hoping the asgard doesn't take as long to release

**Comment by jeffg2k** [comment]
While in-game, the Wraith are still in-work.  We still have a bit to do on balance, research, etc.  But yeah, we got a lot of their assets in and a good bit of the UI and some research completed.
