### ISSUE TITLE
Quicksilver hive ability crash

### ISSUE THREAD

**Issue by jhuddle1** [StargateInvasion/SGI#118]
whenever I build the quicksilver hive it crashes the game once I enter the option to research abilities it has, I cant research the abilities it crashes every time is this not worked on yet ? the hive itself is a wonderful model id love to use it, but cant.

**Comment by jeffg2k** [comment]
Thanks for the report - I've been able to reproduce the error and will investigate the cause.

**Comment by jeffg2k** [comment]
Fixed and changes pushed up
