### ISSUE TITLE
Increase the overview popup size

### ISSUE THREAD

**Issue by jeffg2k** [StargateInvasion/SGI#15]
Many of our weapon or ability names would benefit from a size increase to better fit a longer string.  So we can say "Asgard Pulse Weapons" instead of just "Pulse Weapons" without the name (and level) going over the edge of the gui backdrop as described in #9 

It is likely possible to make the popup information window that displays such ship details wider if we do want to increase the length of these names.

**Comment by AceFighter** [comment]
It is definitely possible, I remember doing this but completely forgot the line of code that implements this.

**Comment by jeffg2k** [comment]
Tau'ri is completed https://github.com/StargateInvasion/SGI/commit/0beb1fb0e8757836379241870bb917003d6b9bfc.  Will adjust Asuran next.

**Comment by jeffg2k** [comment]
Asurans are completed https://github.com/StargateInvasion/SGI/commit/68704cbec7a12f666e3b70b304301615bcd39344
