### ISSUE TITLE
Log Errors

### ISSUE THREAD

**Issue by jeffg2k** [StargateInvasion/SGI#18]
Here are some errors in the log that should be looked at, if they haven't already.  Fixed some already, see below.

~~D3DXCreateEffect Error Buffer: PipelineEffect\Particle_MeshShadowed.fx(114,6): warning X3557: loop only executes for 1 iteration(s), forcing loop to unroll~~

~~D3DXCreateEffect Error Buffer: PipelineEffect\GS_ShadowedAsteroid.fx(114,6): warning X3557: loop only executes for 1 iteration(s), forcing loop to unroll~~

~~D3DXCreateEffect Error Buffer: PipelineEffect\GS_ShadowedShip.fx(255,6): warning X3557: loop only executes for 1 iteration(s), forcing loop to unroll~~

~~PipelineEffect\GS_ShadowedShip.fx(257,7): warning X3557: loop only executes for 1 iteration(s), forcing loop to unroll~~
~~PipelineEffect\GS_ShadowedShip.fx(257,7): warning X3557: loop only executes for 1 iteration(s), forcing loop to unroll~~
~~PipelineEffect\GS_ShadowedShip.fx(128,6): warning X3557: loop only executes for 1 iteration(s), forcing loop to unroll~~

~~*** TextureSystem could not find file (SkinTech) within TextureSystem's working directory (Textures).~~
Reloading All PipelineEffects...
Creating player mappings ... (rand seed:1976703446)
~~Human_FrigateLight_X303 has weapon:0 damage in BACK bank but no weapon points for its current mesh. Is this intended?~~
~~Human_FrigateLight_X303 has weapon:1 damage in FRONT bank but no weapon points for its current mesh. Is this intended?~~
~~Human_FrigateLight_X303 has weapon:2 damage in LEFT bank but no weapon points for its current mesh. Is this intended?~~
~~Human_FrigateLight_X303 has weapon:2 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?~~
~~Human_FrigateLight_X303 has weapon:0 damage in BACK bank but no weapon points for its current mesh. Is this intended?~~
~~Human_FrigateLight_X303 has weapon:1 damage in FRONT bank but no weapon points for its current mesh. Is this intended?~~
~~Human_FrigateLight_X303 has weapon:2 damage in LEFT bank but no weapon points for its current mesh. Is this intended?~~
~~Human_FrigateLight_X303 has weapon:2 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?~~
~~Human_CruiserHeavy_BC304 has weapon:1 damage in LEFT bank but no weapon points for its current mesh. Is this intended?~~
~~Human_CruiserHeavy_BC304 has weapon:1 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?~~
~~Human_CruiserHeavy_BC304 has weapon:1 damage in LEFT bank but no weapon points for its current mesh. Is this intended?~~
~~Human_CruiserHeavy_BC304 has weapon:1 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?~~
~~TITAN_PSIREBEL_COSMETIC has weapon:3 damage in BACK bank but no weapon points for its current mesh. Is this intended?~~
~~Human_TitanDefense_Hephestus_Cosmetic has weapon:0 damage in LEFT bank but no weapon points for its current mesh. Is this intended?~~
~~Human_TitanDefense_Hephestus_Cosmetic has weapon:0 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?~~
~~Human_TitanDefense_Hephestus_Cosmetic has weapon:1 damage in BACK bank but no weapon points for its current mesh. Is this intended?~~
~~Human_TitanDefense_Hephestus_Cosmetic has weapon:1 damage in LEFT bank but no weapon points for its current mesh. Is this intended?~~
~~Human_TitanDefense_Hephestus_Cosmetic has weapon:1 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?~~
~~Human_TitanDefense_Hephestus_Cosmetic has weapon:2 damage in BACK bank but no weapon points for its current mesh. Is this intended?~~
~~Human_TitanDefense_Hephestus_Cosmetic has weapon:3 damage in LEFT bank but no weapon points for its current mesh. Is this intended?~~
~~Human_TitanDefense_Hephestus_Cosmetic has weapon:3 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?~~
~~Human_TitanOffense_Tartarus_Cosmetic has weapon:1 damage in FRONT bank but no weapon points for its current mesh. Is this intended?~~
~~Human_TitanOffense_Tartarus_Cosmetic has weapon:1 damage in BACK bank but no weapon points for its current mesh. Is this intended?~~
~~Human_TitanOffense_Tartarus_Cosmetic has weapon:1 damage in LEFT bank but no weapon points for its current mesh. Is this intended?~~
~~Human_TitanOffense_Tartarus_Cosmetic has weapon:1 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?~~
~~Human_TitanOffense_Tartarus_Cosmetic has weapon:3 damage in LEFT bank but no weapon points for its current mesh. Is this intended?~~
~~Human_TitanOffense_Tartarus_Cosmetic has weapon:3 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?~~
~~TITAN_PHASEREBEL_COSMETIC has weapon:2 damage in BACK bank but no weapon points for its current mesh. Is this intended?~~

**Comment by jeffg2k** [comment]
I fixed the issue: *** TextureSystem could not find file (SkinTech) within TextureSystem's working directory (Textures).

**Comment by jeffg2k** [comment]
I also fixed the D3DXCreateEffect Error Buffer issues.

**Comment by jeffg2k** [comment]
Looking through some forums, I found this information on the error "no weapon points for its current mesh".

> ... group of errors is because you've given ships weapon damage values in an arc that doesn't have mesh points set up for it in the model.  To fix those errors just go into the mesh files used by FrigateTechScout and FrigatePhaseScout and add proper weapon nulls for the left and right arcs.

**Comment by dotNfg** [comment]
Titan Cosmetic entity errors should be fixed now.

**Comment by dotNfg** [comment]
All of the above errors are fixed now, some other similar errors remain. 

Human Hangar Defense  (no weapon points whatsoever but weapon damage numbers so needs to be setup)

Asuran Destiny (need to reoriend mesh points so it can target LEFT/RIGHT

Asuran Nemesis

**Comment by jeffg2k** [comment]
Additional has weapon damage in bank but no weapon points.
Human_Orbital_HangerDefense has weapon:0 damage in FRONT bank but no weapon points for its current mesh. Is this intended?
Human_Orbital_HangerDefense has weapon:0 damage in BACK bank but no weapon points for its current mesh. Is this intended?
Human_Orbital_HangerDefense has weapon:0 damage in LEFT bank but no weapon points for its current mesh. Is this intended?
Human_Orbital_HangerDefense has weapon:0 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?
Human_Orbital_HangerDefense has weapon:0 damage in FRONT bank but no weapon points for its current mesh. Is this intended?
Human_Orbital_HangerDefense has weapon:0 damage in BACK bank but no weapon points for its current mesh. Is this intended?
Human_Orbital_HangerDefense has weapon:0 damage in LEFT bank but no weapon points for its current mesh. Is this intended?
Human_Orbital_HangerDefense has weapon:0 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?
Asuran_CapitalColony_Destiny has weapon:0 damage in LEFT bank but no weapon points for its current mesh. Is this intended?
Asuran_CapitalColony_Destiny has weapon:0 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?
Asuran_CapitalColony_Destiny has weapon:1 damage in LEFT bank but no weapon points for its current mesh. Is this intended?
Asuran_CapitalColony_Destiny has weapon:1 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?
Asuran_CapitalColony_Destiny has weapon:0 damage in LEFT bank but no weapon points for its current mesh. Is this intended?
Asuran_CapitalColony_Destiny has weapon:0 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?
Asuran_CapitalColony_Destiny has weapon:1 damage in LEFT bank but no weapon points for its current mesh. Is this intended?
Asuran_CapitalColony_Destiny has weapon:1 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?
Asuran_FrigateColony_Seedship has weapon:1 damage in BACK bank but no weapon points for its current mesh. Is this intended?
Asuran_FrigateColony_Seedship has weapon:1 damage in LEFT bank but no weapon points for its current mesh. Is this intended?
Asuran_FrigateColony_Seedship has weapon:1 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?
Asuran_FrigateColony_Seedship has weapon:1 damage in BACK bank but no weapon points for its current mesh. Is this intended?
Asuran_FrigateColony_Seedship has weapon:1 damage in LEFT bank but no weapon points for its current mesh. Is this intended?
Asuran_FrigateColony_Seedship has weapon:1 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?
Human_StarbaseOffense_Hades has weapon:0 damage in BACK bank but no weapon points for its current mesh. Is this intended?
Human_StarbaseOffense_Hades has weapon:0 damage in BACK bank but no weapon points for its current mesh. Is this intended?
Human_TitanOffense_Tartarus has weapon:1 damage in FRONT bank but no weapon points for its current mesh. Is this intended?
Human_TitanOffense_Tartarus has weapon:1 damage in FRONT bank but no weapon points for its current mesh. Is this intended?
Human_TitanDefense_Hephestus has weapon:0 damage in LEFT bank but no weapon points for its current mesh. Is this intended?
Human_TitanDefense_Hephestus has weapon:0 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?
Error - No bomb effect points found on bomber: Human_TitanDefense_Hephestus
Human_TitanDefense_Hephestus has weapon:0 damage in LEFT bank but no weapon points for its current mesh. Is this intended?
Human_TitanDefense_Hephestus has weapon:0 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?
Asuran_FrigateCorvette_Nemesis has weapon:0 damage in LEFT bank but no weapon points for its current mesh. Is this intended?
Asuran_FrigateCorvette_Nemesis has weapon:0 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?
Asuran_FrigateCorvette_Nemesis has weapon:1 damage in FRONT bank but no weapon points for its current mesh. Is this intended?
Asuran_FrigateCorvette_Nemesis has weapon:0 damage in LEFT bank but no weapon points for its current mesh. Is this intended?
Asuran_FrigateCorvette_Nemesis has weapon:0 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?
Asuran_FrigateCorvette_Nemesis has weapon:1 damage in FRONT bank but no weapon points for its current mesh. Is this intended?
Asuran_CapitalCarrier_Alastor has weapon:0 damage in LEFT bank but no weapon points for its current mesh. Is this intended?
Asuran_CapitalCarrier_Alastor has weapon:0 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?
Asuran_CapitalCarrier_Alastor has weapon:0 damage in LEFT bank but no weapon points for its current mesh. Is this intended?
Asuran_CapitalCarrier_Alastor has weapon:0 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?
Asuran_FighterBomber_Raptor has weapon:0 damage in FRONT bank but no weapon points for its current mesh. Is this intended?
Asuran_FighterBomber_Raptor has weapon:1 damage in FRONT bank but no weapon points for its current mesh. Is this intended?
Asuran_CruiserAntiModule_Typhaon has weapon:0 damage in FRONT bank but no weapon points for its current mesh. Is this intended?
Asuran_CruiserAntiModule_Typhaon has weapon:1 damage in FRONT bank but no weapon points for its current mesh. Is this intended?
Asuran_CruiserAntiModule_Typhaon has weapon:0 damage in FRONT bank but no weapon points for its current mesh. Is this intended?
Asuran_CruiserAntiModule_Typhaon has weapon:1 damage in FRONT bank but no weapon points for its current mesh. Is this intended?
Asuran_CapitalBattleship_Orion has weapon:1 damage in FRONT bank but no weapon points for its current mesh. Is this intended?
Asuran_CapitalBattleship_Orion has weapon:1 damage in FRONT bank but no weapon points for its current mesh. Is this intended?

**Comment by VikingWarriorGaming** [comment]
Raptor is fixed
