### ISSUE TITLE
Weapon Index Out of Bounds

### ISSUE THREAD

**Issue by jeffg2k** [StargateInvasion/SGI#21]
Issue when showing errors that would love to get fixed.

**Invalid Mesh Point Data String Found by IWeapon (Weapon Index Out of Bounds)**

Mesh = ...\SGI\Mesh\Human_CruiserHeavy_BC304.mesh
MeshPointString = 'Weapon-1'
Parsed Weapon Index = 1
Max Weapon Index = {}

Mesh = ...\SGI\Mesh\Human_CruiserHeavy_BC304.mesh
MeshPointString = 'Weapon-2'
Parsed Weapon Index = 2
Max Weapon Index = {}

Mesh = ...\SGI\Mesh\Human_FrigateAntiFighter_Claudius.mesh
MeshPointString = 'Weapon-1'
Parsed Weapon Index = 1
Max Weapon Index = {}

**Possible duplicate of #18 which has these in the log - same problem?**
Human_CruiserHeavy_BC304 has weapon:1 damage in LEFT bank but no weapon points for its current mesh. Is this intended?
Human_CruiserHeavy_BC304 has weapon:1 damage in RIGHT bank but no weapon points for its current mesh. Is this intended?

**Comment by dotNfg** [comment]
Issue has been resolved.
