### ISSUE TITLE
Reference doesn't exist for Texture

### ISSUE THREAD

**Issue by jeffg2k** [StargateInvasion/SGI#24]
This is a list of textures that don't appear to be referenced from a brush, mesh, etc, sort of the reverse of #19. In this case, we may be able to either delete these textures or add a proper reference to them.  At the moment, this may skip files that reference these textures if the file is a binary.  So if a compiled mesh references one of these textures, it wouldn't be detected.

But we should be able to look at this list and hopefully see things that pop out as possible errors or something we can remove.  If you remove an unused texture, place it in our GD modding folder under ".../Assets/Textures/Unused Textures" in case we want to use it later or for some reason put it back.

- 	Texture not referenced in a game file: acmuzzle2.dds
- 	~~Texture not referenced in a game file: AG3Beam_Glow.dds~~
- 	Texture not referenced in a game file: AncientsDestroyer.dds
- 	Texture not referenced in a game file: Animation_PreRec_Red.tga
- 	Texture not referenced in a game file: Asgard_Buttons_Research_CursorOver.tga
- 	Texture not referenced in a game file: Asgard_Buttons_Research_Disabled.tga
- 	Texture not referenced in a game file: Asgard_Buttons_Research_Normal.tga
- 	Texture not referenced in a game file: Asgard_Buttons_Research_Pressed.tga
- 	Texture not referenced in a game file: Asgard_CapitalBattleship.dds
- 	Texture not referenced in a game file: Asgard_CapitalCarrier.dds
- 	Texture not referenced in a game file: Asgard_CapitalSiege.dds
- 	Texture not referenced in a game file: Asgard_CapitalSupport.dds
- 	Texture not referenced in a game file: Asgard_FrigateLight.dds
- 	Texture not referenced in a game file: AsgardBeliskner.dds
- 	Texture not referenced in a game file: AsgardDreadnaught.dds
- 	Texture not referenced in a game file: AsgardGungnir.dds
- 	Texture not referenced in a game file: AsgardMjolnir.dds
- 	Texture not referenced in a game file: AsgardONeill.dds
- 	Texture not referenced in a game file: Asteroid.dds
- 	Texture not referenced in a game file: AsteroidBig00.dds
- 	Texture not referenced in a game file: AsteroidBig01.dds
- 	Texture not referenced in a game file: AsteroidBig02.dds
- 	Texture not referenced in a game file: AsteroidBig03.dds
- 	Texture not referenced in a game file: AsteroidBig04.dds
- 	Texture not referenced in a game file: AsteroidSmall00.dds
- 	Texture not referenced in a game file: AsteroidSmall01.dds
- 	Texture not referenced in a game file: AsteroidSmall02.dds
- 	Texture not referenced in a game file: AsteroidSmall03.dds
- 	Texture not referenced in a game file: AsteroidSmall04.dds
- 	Texture not referenced in a game file: AsteroidSmall05.dds
- 	Texture not referenced in a game file: AsteroidSmall06.dds
- 	Texture not referenced in a game file: Asuran_CruiserStarBaseConstructor_Rhea.dds
- 	Texture not referenced in a game file: Asuran_Drones_animation.dds
- 	Texture not referenced in a game file: Asuran_Orbital_Extractor.dds
- 	Texture not referenced in a game file: Asuran_Orbital_HeadQuarters.dds
- 	Texture not referenced in a game file: Atlantis_Shield-CL.dds
- 	Texture not referenced in a game file: AtlantisShield.dds
- 	Texture not referenced in a game file: atomiccloud2_green.tga
- 	Texture not referenced in a game file: atomiccloud2_purple.tga
- 	Texture not referenced in a game file: atomiccloud4_borg.dds
- 	Texture not referenced in a game file: autocannon.tga
- 	Texture not referenced in a game file: backdropfrontend_m0d.dds
- 	Texture not referenced in a game file: BlackHole.dds
- 	Texture not referenced in a game file: blank.dds
- 	Texture not referenced in a game file: BlankTexture-CL.dds
- 	Texture not referenced in a game file: BlankTexture-DA.dds
- 	Texture not referenced in a game file: BlankTexture-NM.dds
- 	Texture not referenced in a game file: boltz.dds
- 	Texture not referenced in a game file: BrokenPlanet.dds
- 	Texture not referenced in a game file: CannonShellPhase.dds
- 	Texture not referenced in a game file: CapitalAbilityBeamBlast_Core.dds
- 	Texture not referenced in a game file: CapitalAbilityBeamBlast_Glow.dds
- 	Texture not referenced in a game file: CapitalPhaseCarrier.dds
- 	Texture not referenced in a game file: chaosbolt.dds
- 	Texture not referenced in a game file: Cheop.dds
- 	Texture not referenced in a game file: cloudgauss2.dds
- 	Texture not referenced in a game file: CometTexture.dds
- 	Texture not referenced in a game file: Corsair1.dds
- 	Texture not referenced in a game file: Cursor.tga
- 	Texture not referenced in a game file: Cursor_AllyPingAttack.tga
- 	Texture not referenced in a game file: Cursor_AllyPingDefend.tga
- 	Texture not referenced in a game file: Cursor_Attack.tga
- 	Texture not referenced in a game file: Cursor_CapitalShip_Move.tga
- 	Texture not referenced in a game file: Cursor_CapitalShip_UseAbility.tga
- 	Texture not referenced in a game file: Cursor_Focus.tga
- 	Texture not referenced in a game file: Cursor_InvalidAction.tga
- 	Texture not referenced in a game file: Cursor_ModulePlacement.tga
- 	Texture not referenced in a game file: Cursor_Ping.tga
- 	Texture not referenced in a game file: Cursor_Pingpeace.tga
- 	Texture not referenced in a game file: Cursor_RightClickAttack.tga
- 	Texture not referenced in a game file: Cursor_RightClickMove.tga
- 	Texture not referenced in a game file: Cursor_SetRallyPoint.tga
- 	Texture not referenced in a game file: DebrisAdventLarge.dds
- 	Texture not referenced in a game file: DebrisAdventMaster.dds
- 	Texture not referenced in a game file: DebrisGenericTech0.dds
- 	Texture not referenced in a game file: DebrisGenericTech1.dds
- 	Texture not referenced in a game file: DebrisGenericTech2.dds
- 	Texture not referenced in a game file: DebrisPhaseCapitalBattleship.dds
- 	Texture not referenced in a game file: DebrisPhaseCapitalCarrier.dds
- 	Texture not referenced in a game file: DebrisPhaseCapitalColony.dds
- 	Texture not referenced in a game file: DebrisPhaseGenericLarge0.dds
- 	Texture not referenced in a game file: DebrisPhaseGenericLarge1.dds
- 	Texture not referenced in a game file: DebrisPhaseGenericLarge2.dds
- 	Texture not referenced in a game file: DebrisPhaseGenericSmall0.dds
- 	Texture not referenced in a game file: DebrisTechLarge.dds
- 	Texture not referenced in a game file: Debug.dds
- 	Texture not referenced in a game file: EffectPhaseCapitalmissile.dds
- 	Texture not referenced in a game file: EffectPhaseClusterbomb.dds
- 	Texture not referenced in a game file: EffectPhaseColonypod.dds
- 	Texture not referenced in a game file: EffectPhaseFightermissile.dds
- 	Texture not referenced in a game file: EffectPhasePlanetelevator.dds
- 	Texture not referenced in a game file: EffectPhaseRaze.dds
- 	Texture not referenced in a game file: EffectPsiColonypod.dds
- 	Texture not referenced in a game file: EffectPsiKinetic.dds
- 	Texture not referenced in a game file: EffectPsiPlanetelevator.dds
- 	Texture not referenced in a game file: EffectPsiPlasmabomb.dds
- 	Texture not referenced in a game file: EffectTechActurret.dds
- 	Texture not referenced in a game file: EffectTechCapitalmissile.dds
- 	Texture not referenced in a game file: EffectTechColonypod.dds
- 	Texture not referenced in a game file: EffectTechCruiserMissile.dds
- 	Texture not referenced in a game file: EffectTechFlackguns.dds
- 	Texture not referenced in a game file: EffectTechInvasionpod.dds
- 	Texture not referenced in a game file: EffectTechLaserturret.dds
- 	Texture not referenced in a game file: EffectTechMissiletower.dds
- 	Texture not referenced in a game file: EffectTechMissileturret.dds
- 	Texture not referenced in a game file: EffectTechPlanetelevator.dds
- 	Texture not referenced in a game file: EffectTechPlanetElevatorBunker.dds
- 	Texture not referenced in a game file: EffectTechPlanetElevatorCultureCenter.dds
- 	Texture not referenced in a game file: EffectTechPlanetElevatorExtractor.dds
- 	Texture not referenced in a game file: EffectTechPlanetElevatorGoodsFactory.dds
- 	Texture not referenced in a game file: EffectTechPlanetElevatorProductionCenter.dds
- 	Texture not referenced in a game file: EffectTechPlanetElevatorResourceRefinery.dds
- 	Texture not referenced in a game file: EffectTechProbe.dds
- 	Texture not referenced in a game file: EffectTechRepairship.dds
- 	Texture not referenced in a game file: EffectTechsupportmissile.dds
- 	Texture not referenced in a game file: Eidolo_Ring_Effect_partial.tga
- 	Texture not referenced in a game file: event_horizon.tga
- 	Texture not referenced in a game file: ExhaustTrail.dds
- 	Texture not referenced in a game file: explosion_capital.tga
- 	Texture not referenced in a game file: explosion_core_2.tga
- 	Texture not referenced in a game file: explosion_core_2_debris.tga
- 	Texture not referenced in a game file: explosion_core_4.tga
- 	Texture not referenced in a game file: explosion_core_5.dds
- 	Texture not referenced in a game file: explosion_core_6.tga
- 	Texture not referenced in a game file: explosion_core_6_flare.tga
- 	Texture not referenced in a game file: explosion_core_green1.tga
- 	Texture not referenced in a game file: explosion_core_green2.tga
- 	Texture not referenced in a game file: explosion_core_green3.tga
- 	Texture not referenced in a game file: explosion_core_purple.tga
- 	Texture not referenced in a game file: explosion_core_purple1.tga
- 	Texture not referenced in a game file: explosion_core_purple2.tga
- 	Texture not referenced in a game file: explosion_core_purple3.tga
- 	Texture not referenced in a game file: Explosion_Core_Yellow.tga
- 	Texture not referenced in a game file: explosion_flare_1.tga
- 	Texture not referenced in a game file: explosionbig_core_green1.tga
- 	Texture not referenced in a game file: F302-CL.dds
- 	Texture not referenced in a game file: F302-DA.dds
- 	Texture not referenced in a game file: F302-NM.dds
- 	Texture not referenced in a game file: FactionSelectScreen_Buttons_CursorOver.tga
- 	Texture not referenced in a game file: FactionSelectScreen_Buttons_Normal.tga
- 	Texture not referenced in a game file: FactionSelectScreen_Buttons_Pressed.tga
- 	Texture not referenced in a game file: fireyflair.dds
- 	Texture not referenced in a game file: flare1_purple.tga
- 	Texture not referenced in a game file: flare1_rays.tga
- 	Texture not referenced in a game file: flare2_rays.tga
- 	Texture not referenced in a game file: flare_blue.tga
- 	Texture not referenced in a game file: flare_green.tga
- 	Texture not referenced in a game file: flare_green2.tga
- 	Texture not referenced in a game file: flare_streak.tga
- 	Texture not referenced in a game file: flare_yellow.tga
- 	Texture not referenced in a game file: fusion_flash.tga
- 	Texture not referenced in a game file: greenblock.dds
- 	Texture not referenced in a game file: Grey.dds
- 	Texture not referenced in a game file: HiveDestroyShockwave.dds
- 	Texture not referenced in a game file: Human_CapitalHero_Apollo.dds
- 	Texture not referenced in a game file: Human_CapitalHero_Daedalus.dds
- 	Texture not referenced in a game file: Human_CapitalHero_Odyssey.dds
- 	Texture not referenced in a game file: Human_CruiserStarBaseConstructor_Hera.dds
- 	Texture not referenced in a game file: Human_FighterSpecial_S412.dds
- 	Texture not referenced in a game file: Human_ModuleRefineryShip_Demeter.dds
- 	Texture not referenced in a game file: Human_Orbital_HangerDefense2.dds
- 	Texture not referenced in a game file: Human_Orbital_RepairBay.dds
- 	Texture not referenced in a game file: Human_Orbital_ShieldGenerator.dds
- 	Texture not referenced in a game file: HyperspaceTravel.dds
- 	Texture not referenced in a game file: Icons_planets_maelstrom.dds
- 	Texture not referenced in a game file: JoshBeam_Glow.dds
- 	Texture not referenced in a game file: JoshlBeam_Core.dds
- 	Texture not referenced in a game file: Kay-Bubbles.tga
- 	Texture not referenced in a game file: Kay-friction2.tga
- 	Texture not referenced in a game file: Kay_beam2.tga
- 	Texture not referenced in a game file: Kay_open1.dds
- 	Texture not referenced in a game file: Kay_open2.dds
- 	Texture not referenced in a game file: Kay_softray.tga
- 	Texture not referenced in a game file: Kay_sphere.dds
- 	Texture not referenced in a game file: lensflare1.dds
- 	Texture not referenced in a game file: lightning_animation_pointed.tga
- 	Texture not referenced in a game file: LoadingSplash.tga
- 	Texture not referenced in a game file: Logo_Diplomacy.tga
- 	Texture not referenced in a game file: M_O_Blkhle.dds
- 	Texture not referenced in a game file: MasterPirate.dds
- 	Texture not referenced in a game file: mini_spark.tga
- 	Texture not referenced in a game file: Moon00.dds
- 	Texture not referenced in a game file: MoonType1.DDS
- 	Texture not referenced in a game file: MoonType2.DDS
- 	Texture not referenced in a game file: nanitefriendly2.tga
- 	Texture not referenced in a game file: NoNormal.dds
- 	Texture not referenced in a game file: NoTexture.dds
- 	Texture not referenced in a game file: OriDeliverance.dds
- 	Texture not referenced in a game file: OriSovereign.dds
- 	Texture not referenced in a game file: PhaseCapitalBeam_Core_Medium_Red.dds
- 	Texture not referenced in a game file: phasewave1.tga
- 	Texture not referenced in a game file: phasewave2.dds
- 	Texture not referenced in a game file: phasewave3.dds
- 	Texture not referenced in a game file: Planet_Jungle.dds
- 	Texture not referenced in a game file: Planet_Occupation_Structure.dds
- 	Texture not referenced in a game file: Planet_OccupationStructure.dds
- 	Texture not referenced in a game file: PlanetArtifact.dds
- 	Texture not referenced in a game file: PlanetBarren.dds
- 	Texture not referenced in a game file: PlanetBlack.dds
- 	Texture not referenced in a game file: PlanetCloudLayer.dds
- 	Texture not referenced in a game file: PlanetDarkSideLights.dds
- 	Texture not referenced in a game file: PlanetDesert01.dds
- 	Texture not referenced in a game file: PlanetDesert02.dds
- 	Texture not referenced in a game file: PlanetDwarf00.dds
- 	Texture not referenced in a game file: PlanetDwarf01.dds
- 	Texture not referenced in a game file: PlanetElevatorCars.dds
- 	Texture not referenced in a game file: Planetgas0.dds
- 	Texture not referenced in a game file: Planetgas1.dds
- 	Texture not referenced in a game file: PlanetGreenhouse.dds
- 	Texture not referenced in a game file: PlanetIron.dds
- 	Texture not referenced in a game file: planetmania.dds
- 	Texture not referenced in a game file: PlanetMoon10.dds
- 	Texture not referenced in a game file: PlanetMoon12.dds
- 	Texture not referenced in a game file: PlanetMoon13.dds
- 	Texture not referenced in a game file: PlanetMoon4.dds
- 	Texture not referenced in a game file: PlanetMoon5.dds
- 	Texture not referenced in a game file: PlanetMoon6.dds
- 	Texture not referenced in a game file: PlanetMoon7.dds
- 	Texture not referenced in a game file: PlanetOcean01.dds
- 	Texture not referenced in a game file: PlanetOceanic00.dds
- 	Texture not referenced in a game file: PlanetParadise.dds
- 	Texture not referenced in a game file: PlanetPirateBase.dds
- 	Texture not referenced in a game file: PlanetRings.dds
- 	Texture not referenced in a game file: PlanetRockGiantHabitable.dds
- 	Texture not referenced in a game file: PlanetTerran01.dds
- 	Texture not referenced in a game file: PlanetTerran02.dds
- 	Texture not referenced in a game file: PlanetTerranGiantHabitable.dds
- 	Texture not referenced in a game file: PlanetToxic.dds
- 	Texture not referenced in a game file: plasma_electric.tga
- 	Texture not referenced in a game file: plasma_hit.tga
- 	Texture not referenced in a game file: plating_color.PSD
- 	Texture not referenced in a game file: plating_normals.PSD
- 	Texture not referenced in a game file: plnt-Gate-CL.dds
- 	Texture not referenced in a game file: plnt-Gate-DA.dds
- 	Texture not referenced in a game file: plnt-Gate-NM.dds
- 	Texture not referenced in a game file: preswoosh.tga
- 	Texture not referenced in a game file: preswoosh2.tga
- 	Texture not referenced in a game file: psicolony-team.dds
- 	Texture not referenced in a game file: psicolonyfrigate-team.dds
- 	Texture not referenced in a game file: psifriendlyspotsblue.tga
- 	Texture not referenced in a game file: psiplasma.tga
- 	Texture not referenced in a game file: psiplasmahitmuzzle.tga
- 	Texture not referenced in a game file: psiryhull-team.dds
- 	Texture not referenced in a game file: psitempleofcommunion-team.dds
- 	Texture not referenced in a game file: pulsar_texture.dds
- 	Texture not referenced in a game file: pushhand.dds
- 	Texture not referenced in a game file: Races_PlayerSetup.dds
- 	Texture not referenced in a game file: Races_Unit_Hud_CursorOver.tga
- 	Texture not referenced in a game file: Races_Unit_Hud_Disabled.tga
- 	Texture not referenced in a game file: Races_Unit_Hud_Normal.tga
- 	Texture not referenced in a game file: Races_Unit_Hud_Pressed.tga
- 	Texture not referenced in a game file: Races_Unit_Infocard.tga
- 	Texture not referenced in a game file: Races_Unit_Main.tga
- 	Texture not referenced in a game file: Races_Unit_Picture.dds
- 	Texture not referenced in a game file: radiationbombbuff.dds
- 	Texture not referenced in a game file: radiationbombbuffsmall.dds
- 	Texture not referenced in a game file: rayoflight_borg.dds
- 	Texture not referenced in a game file: rayoflightout_borg.dds
- 	Texture not referenced in a game file: rays_bluegreen.tga
- 	Texture not referenced in a game file: rays_purpleyellow.tga
- 	Texture not referenced in a game file: RefineryshipTech.dds
- 	Texture not referenced in a game file: RelationShipUnderlay.dds
- 	Texture not referenced in a game file: resourcedrain_magic.dds
- 	Texture not referenced in a game file: rock.dds
- 	Texture not referenced in a game file: ScenarioPicture-all species.tga
- 	Texture not referenced in a game file: ScenarioPicture-anubis.tga
- 	Texture not referenced in a game file: ScenarioPicture-apophis.tga
- 	Texture not referenced in a game file: ScenarioPicture-asgard high council.tga
- 	Texture not referenced in a game file: ScenarioPicture-asgard roundom 2.tga
- 	Texture not referenced in a game file: ScenarioPicture-asurans.tga
- 	Texture not referenced in a game file: ScenarioPicture-Atlantis expedition.tga
- 	Texture not referenced in a game file: ScenarioPicture-baal.tga
- 	Texture not referenced in a game file: ScenarioPicture-BattleLinesFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-BlitzFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-CloseEncountersFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-cronus.tga
- 	Texture not referenced in a game file: ScenarioPicture-Default.tga
- 	Texture not referenced in a game file: ScenarioPicture-DoubleCrossFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-EntanglementFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-ForeignInvasionFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-FracturedLandsFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-gaiancrescent.tga
- 	Texture not referenced in a game file: ScenarioPicture-GainCrescent.tga
- 	Texture not referenced in a game file: ScenarioPicture-GeminiFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-goa uld random.tga
- 	Texture not referenced in a game file: ScenarioPicture-hathor.tga
- 	Texture not referenced in a game file: ScenarioPicture-heru ur.tga
- 	Texture not referenced in a game file: ScenarioPicture-human empire.tga
- 	Texture not referenced in a game file: ScenarioPicture-human systemlord.tga
- 	Texture not referenced in a game file: ScenarioPicture-IOA.tga
- 	Texture not referenced in a game file: ScenarioPicture-jaffa.tga
- 	Texture not referenced in a game file: ScenarioPicture-lanteans.tga
- 	Texture not referenced in a game file: ScenarioPicture-MaelstromFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-MeltingPointFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-NewDawnFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-osiris.tga
- 	Texture not referenced in a game file: ScenarioPicture-PandemoniumFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-pegasus galaxy random.tga
- 	Texture not referenced in a game file: ScenarioPicture-QuickStrikeFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-ra.tga
- 	Texture not referenced in a game file: ScenarioPicture-RandomHugeFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-RandomHugeRingFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-RandomLargeFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-RandomMediumFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-RandomMiniFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-RandomSmallFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-RandomVastFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-RazorsEdgeFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-small.tga
- 	Texture not referenced in a game file: ScenarioPicture-sokar.tga
- 	Texture not referenced in a game file: ScenarioPicture-StormfrontFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-TempestFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-TripleEntenteFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-TwinEmpiresFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-TyphoonFair.tga
- 	Texture not referenced in a game file: ScenarioPicture-US.tga
- 	Texture not referenced in a game file: ScenarioPicture-vanir.tga
- 	Texture not referenced in a game file: ScenarioPicture-very smal.tga
- 	Texture not referenced in a game file: ScenarioPicture-wraith.tga
- 	Texture not referenced in a game file: ScenarioPicture-yu.tga
- 	Texture not referenced in a game file: sensororange.dds
- 	Texture not referenced in a game file: sensorrange.dds
- 	Texture not referenced in a game file: SGachill-CL.dds
- 	Texture not referenced in a game file: SGachill-DA.dds
- 	Texture not referenced in a game file: SGachill-NM.dds
- 	Texture not referenced in a game file: sgi_logo.tga
- 	Texture not referenced in a game file: sgi_menu_quit.tga
- 	Texture not referenced in a game file: shockfront.tga
- 	Texture not referenced in a game file: shockfront_b_w.tga
- 	Texture not referenced in a game file: shockfront_bluegreen.tga
- 	Texture not referenced in a game file: shockwaveborgcloud.dds
- 	Texture not referenced in a game file: skinpart.dds
- 	Texture not referenced in a game file: skull.dds
- 	Texture not referenced in a game file: SkyboxBackdrop1.dds
- 	Texture not referenced in a game file: SkyboxBackdrop10.dds
- 	Texture not referenced in a game file: SkyboxBackdrop11.dds
- 	Texture not referenced in a game file: SkyboxBackdrop2.dds
- 	Texture not referenced in a game file: SkyboxBackdrop3.dds
- 	Texture not referenced in a game file: SkyboxBackdrop4.dds
- 	Texture not referenced in a game file: SkyboxBackdrop5.dds
- 	Texture not referenced in a game file: SkyboxBackdrop6.dds
- 	Texture not referenced in a game file: SkyboxBackdrop7.dds
- 	Texture not referenced in a game file: SkyboxBackdrop8.dds
- 	Texture not referenced in a game file: SkyboxBackdrop9.dds
- 	Texture not referenced in a game file: smoke.dds
- 	Texture not referenced in a game file: smoke_black.dds
- 	Texture not referenced in a game file: sparksarray.dds
- 	Texture not referenced in a game file: sparksarrayphase.dds
- 	Texture not referenced in a game file: sparksarraypsi.dds
- 	Texture not referenced in a game file: StarBasePsi.dds
- 	Texture not referenced in a game file: starblue.dds
- 	Texture not referenced in a game file: starcorerk.dds
- 	Texture not referenced in a game file: starcore-white.dds
- 	Texture not referenced in a game file: starcore-yellow.dds
- 	Texture not referenced in a game file: starcorona.dds
- 	Texture not referenced in a game file: starfield.dds
- 	Texture not referenced in a game file: StargateActivation.tga
- 	Texture not referenced in a game file: stargreen.dds
- 	Texture not referenced in a game file: starneutron.dds
- 	Texture not referenced in a game file: starpulsar.dds
- 	Texture not referenced in a game file: starquasar.dds
- 	Texture not referenced in a game file: starred.dds
- 	Texture not referenced in a game file: StarscapeStar0.dds
- 	Texture not referenced in a game file: StarscapeStar1.dds
- 	Texture not referenced in a game file: StarscapeStar2.dds
- 	Texture not referenced in a game file: starwhite.dds
- 	Texture not referenced in a game file: staryellow.dds
- 	Texture not referenced in a game file: steamjet.dds
- 	Texture not referenced in a game file: SubHive.dds
- 	Texture not referenced in a game file: swoosh.tga
- 	Texture not referenced in a game file: target.dds
- 	Texture not referenced in a game file: TechCapitalBeam_Core.dds
- 	Texture not referenced in a game file: TechCapitalBeam_Glow.dds
- 	Texture not referenced in a game file: techcapitalbeamcorona2.tga
- 	Texture not referenced in a game file: techcapitalbeamcorona3.tga
- 	Texture not referenced in a game file: techcapitallaser.dds
- 	Texture not referenced in a game file: TechDroid1.dds
- 	Texture not referenced in a game file: TechDroid2.dds
- 	Texture not referenced in a game file: techfighterion-front.dds
- 	Texture not referenced in a game file: Test.dds
- 	Texture not referenced in a game file: turbulence.dds
- 	Texture not referenced in a game file: TurretSiege.dds
- 	Texture not referenced in a game file: U1-PlayerPicsWindow.dds
- 	Texture not referenced in a game file: Wraith.tga
- 	Texture not referenced in a game file: xin_explosioncloud.tga
- 	Texture not referenced in a game file: autocannon_bluebeam.texanim
- 	Texture not referenced in a game file: autocannon_redbeam.texanim
- 	Texture not referenced in a game file: autocannon_yellowbeam.texanim
- 	Texture not referenced in a game file: Drone_Asuran.texanim
- 	Texture not referenced in a game file: flare_streak.texanim
- 	Texture not referenced in a game file: lightning_simple_pointed.texanim
- 	Texture not referenced in a game file: planetcars.texanim
- 	Texture not referenced in a game file: resourcedrain.texanim

**Comment by dotNfg** [comment]
The AG3 Beam Glow can be removed. It was too simple as a texture and I replaced it with the vanilla beam texture.
