### ISSUE TITLE
Ouranos Constructor effect direction

### ISSUE THREAD

**Issue by jeffg2k** [StargateInvasion/SGI#25]
The building "effect" for the Ouranos Constructor is pointing in the wrong direction.  Instead of the effect emanating in front of the ship to the construction target, the effect emanates from the side of the ship into nothing.

The asuran colony capital also seem to have a few instances where it's drones were off from the target.

**Comment by dotNfg** [comment]
This is a model hard points issue. Result of hard point alignment due to Sins rotation calculation being somehow different to the one in XSI. Needs to be fixed either in the .mesh file or by re-exporting the mesh with the hard point rotation reversed.

**Comment by dotNfg** [comment]
Added an ability point to the mesh which fixed the issue.
