### ISSUE TITLE
Missing Reference

### ISSUE THREAD

**Issue by AceFighter** [StargateInvasion/SGI#3]
File: Asuran_BuffTitan_MegaBeamActivated.entity
Line: 61
Contents:
conditionBuffShortName "IDS_BUFFSHORTNAME_ASURANTITANMATTERBRIDGE"

Above reference is missing. Also don't know what "conditionBuffShortName" actually does. Is it supposed to be linking into a entity file or the String file?

**Comment by jeffg2k** [comment]
Fixed by @dotNfg in https://github.com/StargateInvasion/SGI/commit/ef30b556965c44abbc2a25bb9eae8cba376a3eab
