### ISSUE TITLE
SG1 Replicators as Pirates

### ISSUE THREAD

**Issue by dotNfg** [StargateInvasion/SGI#32]
The pirates will be replaced by the replicators from SG1 but currently they use Human ships only. For the change to happen we need the following:

1 Smart Material defining replicator blocks, possibly to be blended into existing ship textures.
1 Smart Material for the 5th replicator ship.
3 Replicator specific ships (5th capital ship, 5th cruiser, unique ship that appears in two of the episodes)

**Comment by jeffg2k** [comment]
The [Pegasus Chronicles](https://www.moddb.com/mods/stargate-empire-at-war/news/replicators) put out some replicator ships last year.  We should contact them to see what we may be able to use in SGI.

![replifleet_render](https://user-images.githubusercontent.com/161904/51085702-1e2f3480-170b-11e9-9363-cbf16ac0de69.png)
