### ISSUE TITLE
Texture remaining Asuran Models

### ISSUE THREAD

**Issue by dotNfg** [StargateInvasion/SGI#35]
Texture any remaining Asuran Models

**Comment by jeffg2k** [comment]
### Model Textures Remaining

- Asuran_CruiserStarBaseConstructor_Rhea
- Asuran_Orbital_CapitalShipFactory
- Asuran_Orbital_CombatLaboratory
- Asuran_Orbital_FrigateFactory
- Asuran_Orbital_HangarDefense
- Asuran_Orbital_HeavyDefense
- Asuran_Orbital_JumpBlocker
- Asuran_Orbital_LagrangianSatellite
- Asuran_Orbital_Mine
- Asuran_Orbital_NonCombatLaboratory
- Asuran_Orbital_Refinery  (Same model as Tradeport - need new model)
- Asuran_Orbital_ShieldGenerator
- Asuran_Orbital_TitanFactory
- Asuran_Orbital_TradePort
- Asuran_Orbital_WeaponsPlatform
- Human_StarbaseSpecial_Zeus (Currently used by Asuran unless we fix the Asuran Model Weapon points)
