### ISSUE TITLE
Remove Unused Stock Entity Files

### ISSUE THREAD

**Issue by AceFighter** [StargateInvasion/SGI#50]
Just have to remove those leftover files from the stock game, Specifically those that are in the GameInfo folder

**Comment by jeffg2k** [comment]
The [SinsModCheck](https://github.com/StargateInvasion/SinsModCheck) script should help identify items.

**Comment by jeffg2k** [comment]
I created a new branch that converts the remaining BIN files to TXT so that they can be properly checked for referenced files.

**Comment by jeffg2k** [comment]
We still have a few left, but they're directly related to SGI.  Abilities that we haven't yet implemented and I'm not sure if we want to delete them yet, even though they're currently unused.
