### ISSUE TITLE
Asuran Pulse Weapons listed as Lasers

### ISSUE THREAD

**Issue by jeffg2k** [StargateInvasion/SGI#52]
Asurans have a Pulse Weapon that is applied to most ships.  The research lists and describes it as a pulse weapon and the effects displayed when the weapon fires is that of a pulse weapon.  However, the ship infocard that displays damage lists these weapons as Lasers.  The nomenclature of Lasers is confusing and may lead the users to research beam weapons, rather than pulse weapons, when trying to upgrade this ability.

Currently, these weapons are listed: 
> WeaponClassType "WAVE"

In order to display the weapon as a pulse weapon, this may need to be changed to one of the following.
> WeaponClassType "PULSEGUN"
> WeaponClassType "PULSEWAVE"

This would need to be done on the ships that have this weapon and on the research "linkedWeaponClass".  These are easy changes, but further research may need to be done to verify such a change doesn't unintendedly effect the game.

**Comment by jeffg2k** [comment]
As a reference, here are some of the categories as described in a [Sins Mod post](https://forums.sinsofasolarempire.com/363316/get;2366894):

here's the weapon class types, by their entity designation name and strings designation-

- AUTOCANNON- Autocannon
- MISSILE- Missile
- LASERTECH- Laser
- BEAM- Beam
- LASERPSI- Laser
- PLASMA- Plasma
- WAVE- Wave
- PULSEGUN- Pulse Gun
- FLASHBEAM- Pulse Beam
- PHASEMISSILE- Phase Missile

And now for the special ones, that are UNUSED-

- DART- Kinetic Bolt (I made a mod that used the three unused types; the syntax was changed to DART=Railgun, PLANETBOMBARDMENT=Fusion Blaster, and ION=Ion Cannon
- PLANETBOMBARDMENT- Planet Bombardment
- ION- Ion

**Comment by VikingWarriorGaming** [comment]
All Wave weapons changed to Pulse gun for Asurans should have gotten them all
