### ISSUE TITLE
Asuran Starbase crashing

### ISSUE THREAD

**Issue by jeffg2k** [StargateInvasion/SGI#67]
Testing Blacknife's savegame - it looks like the Asuran Starbase might be the cause. If I pause the game, I can go around clicking on things and disassembling.  Soon as I try to disassemble the starbase, it crashes.  Using shift+s or just hovering over the scuttle button crashes it.  One starbase is close to destruction, which may be the event that causes the crash outside of clicking scuttle.  I'm thinking the bug maybe some element that triggers when a starbase gets destroyed or scuttled.

**Comment by AceFighter** [comment]
Fixed in commit b0523ac31f8fc0a1e3fa1851a99abe703a822d66
