### ISSUE TITLE
Game is stuck when starting up

### ISSUE THREAD

**Issue by Sir-E** [StargateInvasion/SGI#86]
The game gets stuck on this screen when launching.
![Screenshot](https://user-images.githubusercontent.com/43330857/48598043-c7c59580-e915-11e8-9daa-f7129a1d0ebc.png)

**Comment by jeffg2k** [comment]
Make sure you sync to the latest repository code. The Sins GDPR update 1.92 broke all the mods that use a custom start screen.  We pushed a patch to fix it in July.
