### ISSUE TITLE
ZPM Artifact & update on release of wraith or asgard? 

### ISSUE THREAD

**Issue by jhuddle1** [StargateInvasion/SGI#87]
Was wondering when we will see a release of the wraith or asgard ? the wraith seemed done pretty much to me in earlier releases. Also noticed that the zpm extra reaserch in both the asuran and tauri are not able to be researched. this is under the tree that lets you research planetary shields and minefields. I cant research them at all, its blanked out , even though I have necessary requirements unlocked.....

**Comment by jeffg2k** [comment]
We're still working on textures for the Asurans.  Once that's done, we'll move on to the Wraith.  The ZPM extra was something tied into Artifacts.  We'll have to look into that.  We took a break after the Goa'uld release, but we're moving along again.

**Comment by jhuddle1** [comment]
there isnt enough of them to be able to research it, i havent found a single map with the zpm artifact .......

**Comment by jeffg2k** [comment]
Specific artifacts are not assigned - they're semi-random.  SGI increased the chances of finding artifacts on planets, but not any particular artifact.  I added a research option to the ZPM on the Asurans.  I'll take a look at Human, I thought they had it.
