### ISSUE TITLE
ORI/ capturing ships 

### ISSUE THREAD

**Issue by jhuddle1** [StargateInvasion/SGI#96]
So are the ori gonna be ingame? and how do I capture abandoned ships ? also any update on wraith ?

**Comment by jeffg2k** [comment]
The Ori are a Random Event, so yeah, but we have no plans right now to add them as a separate race.  Not sure how to capture abandoned ships.. Is that an ability on a ship?
For updates, I'd suggest looking at our Discord Channel.  I just posted an update there today.  https://discordapp.com/channels/322849121956528139/322856260280254464
