### ISSUE TITLE
Ori Random events ? 

### ISSUE THREAD

**Issue by jhuddle1** [StargateInvasion/SGI#99]
So I am wondering what triggers the ori random event ? like what maps are needed, what scenarios are more likely to trigger it ?

**Comment by jeffg2k** [comment]
I think it's just random on any map.  It may require the Stellar Phenomena DLC as they're defined as "Mad Vasari".  I'll have to look into it more, but that's as much as I can think of now.

**Comment by jeffg2k** [comment]
I'm thinking we need to increase the frequency on these - it seems pretty rare and I'd like to see them more often.
